config/routes.rb
Finapps::Application.routes.draw do
  match '/inflation',  :to => "inflation#index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  match '/login',  :to => 'sessions#new'   
  resources :sessions
  match '/register',  :to => 'users#new'   
  resources :users
  resources :posts
  resources :blogcats
  match '/adm',  :to => 'adm#index'

  
  get "fvcalc/fvcalc"
  match '/fvcalc',  :to => 'fvcalc#fvcalc'
  match '/fvcalcres',  :to => 'fvcalc#fvcalcres'
  match '/fvcalcs',  :to => 'fvcalc#fvcalcs'
  match '/fvcalcress',  :to => 'fvcalc#fvcalcress'
  match '/math',  :to => 'simpleapps#math'
  match '/simpleapps',  :to => 'simpleapps#index'  
  match '/kubik',  :to => 'simpleapps#kubik'
  match '/decision',  :to => 'simpleapps#decision'
  match '/happydays',  :to => 'simpleapps#happydays'
  match '/capitalcost',  :to => 'simpleapps#capitalcost'
  root :to => 'posts#index'

end

app/models/blogcat.rb
class Blogcat < ActiveRecord::Base
  has_many :posts, :foreign_key => :cat_id
  validates_presence_of :category
  validates_uniqueness_of :category
end

app/controllers/blogcats_controller.rb
class BlogcatsController < ApplicationController
  
  def new
     @cat = Blogcat.new
  end

  def create
    @cat = Blogcat.new(params[:blogcat])

    respond_to do |format|
      if @cat.save
        format.html { redirect_to adm_path, :notice => 'Category was successfully created.' }
        format.json { render :json => @cat, :status => :created, :location => @cat }
      else
        format.html { render :action => "new" }
        format.json { render :json => @cat.errors, :status => :unprocessable_entity }
      end
    end
  end

  def index
    @cats = Blogcat.all

  end

  def destroy
    @cat = Blogcat.find(params[:id])
    @cat.destroy

    respond_to do |format|
      format.html { redirect_to blogcats_url, :notice => 'Category deleted! :)' }
      format.json { head :ok }
    end
  end

  def edit
    @cat = Blogcat.find(params[:id])
  end
  
    def update
    @cat = Blogcat.find(params[:id])

    respond_to do |format|
      if @cat.update_attributes(params[:blogcat])
        format.html { redirect_to adm_path, :notice => 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @cat.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/blogcats_helper.rb
module BlogcatsHelper
end

app/views/blogcats/edit.html.erb
<h1>Editing post</h1>

  <% if @cat.errors.any? %>
    <div class="message warning">

      <ul>
      <% @cat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@cat) do |f| %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Обратно', blogcats_path %>

app/views/blogcats/index.html.erb
<h1>Категории</h1>

<table>
<tr><td># id</td><td>Название категории</td><td>Действия</td>
</tr>		
<% @cats.each do |c| %>
<tr>
<td><%=c.id%>.</td> <td><b><%=c.category%></b></td><td> (<%= link_to 'Редактировать', edit_blogcat_path(c) %> | <%= link_to 'x', c, :confirm => 'Точно? А если подумать?', :method => :delete %>)</td>
</tr>
<% end %>
</table>

<%= link_to 'На главную', root_path %> | <%= link_to 'Добавить >>', new_blogcat_path %>

<p id="notice"><%= notice %></p>

app/views/blogcats/new.html.erb
<h1>Новая категория</h1>

  <% if @cat.errors.any? %>
    <div class="message warning">

      <ul>
      <% @cat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@cat) do |f| %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Обратно', blogcats_path %>