config/routes.rb
Finapps::Application.routes.draw do
  match '/inflation',  :to => "inflation#index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  match '/login',  :to => 'sessions#new'   
  resources :sessions
  match '/register',  :to => 'users#new'   
  resources :users
  resources :posts
  resources :blogcats
  match '/adm',  :to => 'adm#index'

  
  get "fvcalc/fvcalc"
  match '/fvcalc',  :to => 'fvcalc#fvcalc'
  match '/fvcalcres',  :to => 'fvcalc#fvcalcres'
  match '/fvcalcs',  :to => 'fvcalc#fvcalcs'
  match '/fvcalcress',  :to => 'fvcalc#fvcalcress'
  match '/math',  :to => 'simpleapps#math'
  match '/simpleapps',  :to => 'simpleapps#index'  
  match '/kubik',  :to => 'simpleapps#kubik'
  match '/decision',  :to => 'simpleapps#decision'
  match '/happydays',  :to => 'simpleapps#happydays'
  match '/capitalcost',  :to => 'simpleapps#capitalcost'
  root :to => 'posts#index'

end

app/controllers/adm_controller.rb
class AdmController < ApplicationController
  def index
     @cats = Blogcat.all
     @posts = Post.all
     @users = User.all
  end

end

app/helpers/adm_helper.rb
module AdmHelper
end

app/views/adm/index.html.erb
<% if admin_user %>
<div class="column span-16">
<h2>Posts (<%=Post.count%>)</h2>

<table>
<tr><td># id</td><td>Название записи</td><td>Действия</td>
</tr>		
<% @posts.each do |p| %>
<tr>
<td><%=p.id%>.</td> <td><%= link_to p.title, p %></td><td> (<%= link_to 'Редактировать', edit_post_path(p) %> | <%= link_to 'x', p, :confirm => 'Точно? А если подумать?', :method => :delete %>)</td>
</tr>
<% end %>
</table>

<%= link_to 'На главную', root_path %> | <%= link_to 'Добавить >>', new_post_path %>

</div>


<div class="column span-8 last">
<h2>Categories (<%=Blogcat.count%>)</h2>

<table>
<tr><td># id</td><td>Название категории</td><td>Действия</td>
</tr>		
<% @cats.each do |c| %>
<tr>
<td><%=c.id%>.</td> <td><b><%=c.category%></b></td><td> (<%= link_to 'Редактировать', edit_blogcat_path(c) %> | <%= link_to 'x', c, :confirm => 'Точно? А если подумать?', :method => :delete %>)</td>
</tr>
<% end %>
</table>

<%= link_to 'На главную', root_path %> | <%= link_to 'Добавить >>', new_blogcat_path %>

</div>
<div class="column span-16">
<h2>Users (<%=User.count%>)</h2>
<table>
<tr><td># id</td><td>Name</td><td>email</td>
</tr>		
<% @users.each do |u| %>
<tr>
<td><%=u.id%>.</td> <td><b><%=u.name%></b></td><td> <%=u.email%></td>
</tr>
<% end %>
</table>
</div>
<div class="column span-8 last">
<% else %>
Admin area, sorry.
<% end %>

</div>