config/routes.rb
Finapps::Application.routes.draw do
  match '/inflation',  :to => "inflation#index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  match '/login',  :to => 'sessions#new'   
  resources :sessions
  match '/register',  :to => 'users#new'   
  resources :users
  resources :posts
  resources :blogcats
  match '/adm',  :to => 'adm#index'

  
  get "fvcalc/fvcalc"
  match '/fvcalc',  :to => 'fvcalc#fvcalc'
  match '/fvcalcres',  :to => 'fvcalc#fvcalcres'
  match '/fvcalcs',  :to => 'fvcalc#fvcalcs'
  match '/fvcalcress',  :to => 'fvcalc#fvcalcress'
  match '/math',  :to => 'simpleapps#math'
  match '/simpleapps',  :to => 'simpleapps#index'  
  match '/kubik',  :to => 'simpleapps#kubik'
  match '/decision',  :to => 'simpleapps#decision'
  match '/happydays',  :to => 'simpleapps#happydays'
  match '/capitalcost',  :to => 'simpleapps#capitalcost'
  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blogcat
  validates_uniqueness_of :title
  validates_presence_of :title
  validates_presence_of :content
  
  has_friendly_id :title, :use_slug => true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @cat = Blogcat.find(@post.cat_id).category
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new

    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to adm_path, :notice => 'Post was successfully created.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to adm_path, :notice => 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
	<% if admin_user %>
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<script type="text/javascript">
       bkLib.onDomLoaded(function() { nicEditors.allTextAreas({fullPanel : true}) });
</script>
  <div class="field">
    <%= f.label :cat_id %><br />
    <%= f.number_field :cat_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
	<% else %>
	Извините, только для Админчега :)
	<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="container">
<div id="content">	
	<h1>Blog</h1>
<% @posts.each do |post| %>
	<div class="padmin">
			<% if current_user %>
	    <%= link_to 'Edit', edit_post_path(post) %>
	    <%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %>
	    	<% end %>
	</div> 	

	<div class="ptitle">
		<%= link_to post.title, post %>
	</div>
	
	<div class="pinfo">
		
		<span class="pcat"><%= Blogcat.find(post.cat_id).category %></span> — <span class="ptime"><%=post.created_at.strftime("%d.%m.%Y")%></span>
	</div>

	<div class="pcontent">
	    <%= raw post.content %>
	</div>



<% end %>
</div>
</div>

<aside id="sideRight">
<h1>Nav</h1>

<%= link_to 'Simple apps', simpleapps_path %>
</aside>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @post.title %></h2>
<p>
  <%= @cat %>
</p>

<p>
  <%= raw @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<br />
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'finapps'; // required: replace example with your forum shortname

    // The following are highly recommended additional parameters. Remove the slashes in front to use.
    // var disqus_identifier = 'unique_dynamic_id_1234';
    // var disqus_url = 'http://example.com/permalink-to-page.html';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the comments powered by Disqus.</noscript>