config/routes.rb
Finapps::Application.routes.draw do
  match '/inflation',  :to => "inflation#index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  match '/login',  :to => 'sessions#new'   
  resources :sessions
  match '/register',  :to => 'users#new'   
  resources :users
  resources :posts
  resources :blogcats
  match '/adm',  :to => 'adm#index'

  
  get "fvcalc/fvcalc"
  match '/fvcalc',  :to => 'fvcalc#fvcalc'
  match '/fvcalcres',  :to => 'fvcalc#fvcalcres'
  match '/fvcalcs',  :to => 'fvcalc#fvcalcs'
  match '/fvcalcress',  :to => 'fvcalc#fvcalcress'
  match '/math',  :to => 'simpleapps#math'
  match '/simpleapps',  :to => 'simpleapps#index'  
  match '/kubik',  :to => 'simpleapps#kubik'
  match '/decision',  :to => 'simpleapps#decision'
  match '/happydays',  :to => 'simpleapps#happydays'
  match '/capitalcost',  :to => 'simpleapps#capitalcost'
  root :to => 'posts#index'

end

app/controllers/simpleapps_controller.rb
# -*- encoding : utf-8 -*-
class SimpleappsController < ApplicationController
  def kubik

  end

  def decision

    decmas = ["Мне кажется — «да»","Бесспорно","Решено","Вероятнее всего","Хорошие перспективы","Знаки говорят — «да»","Никаких сомнений","Да","Определённо да","Можешь положиться","Пока не ясно, попробуй снова","Спроси позже","Лучше не рассказывать","Сейчас нельзя предсказать","Сконцентрируйся и спроси опять","Даже не думай","Мой ответ — «нет»","По моим данным — «нет»","Перспективы не очень хорошие","Весьма сомнительно"]
    elements = decmas.count
  @decision = decmas[rand(elements)]  
  end

  def happydays
  end
  
  def math
    @xmass = (-20..20).to_a.join(", ")
    @ysqrt = (-20..20).to_a.map{ |i| i ** 2 }.join(", ")
    @ysin = (-20..20).to_a.map{ |i| Math.sin(i)*200+200 }.join(", ")
  end
  
  
    def capitalcost

    
      presentprice = 10000 + rand(500)*10
      averageprof = 10 + rand(5)
      afv = presentprice + presentprice * averageprof/100
      @presentprice = presentprice.to_s
      @averageprof = averageprof.to_s

    sravnenie = 22
    @sravnenie = sravnenie
    @sravnenietimes = (1..sravnenie).to_a.join(", ")#для подписи данных, кол-во сравнений по порядку
    fvtimes = []
    sravnenie.times do
      fvtimes.push afv
    end
    @fvtimes = fvtimes.join(", ")
    
    devimas = []
    newvalues = [] #массив с новыми значениями
    newvaluesdev = []
      sravnenie.times do
        #определяем исход
        ishod = rand(2)
        
        #определяем отклонение
        rando = rand(11)
        deviation = (rando**2)
        
          if ishod == 0
          rfv = afv + (afv * deviation/100)
          else
          rfv = afv - (afv * deviation/100)
          end
  
        devvv = ((rfv.to_f/presentprice.to_f-1)*100)-averageprof.to_f #определяем квадратическое отклонение
        devvver = devvv.to_f**2 * (1/sravnenie.to_f) #с учетом вероятности, вариация
        devimas.push devvver.to_f
        newvalues.push rfv.to_i
        newvaluesdev.push rfv.to_i-afv #deviation
      end
      @newvalues = newvalues.join(", ")
      @newvaluesdev = newvaluesdev.join(", ")
      sum = 0 
      devimas.each do |i|
        sum += i
      end
      dispersia = Math.sqrt(sum)
      @dispersia = dispersia.to_i.to_s
  end

end

app/helpers/simpleapps_helper.rb
module SimpleappsHelper
end

app/views/simpleapps/_menu.html.erb
	<ul id="menutop">
		<li><%= link_to "Кубик", kubik_path %></li>
		<li><%= link_to "Решения", decision_path %></li>
		<li><%= link_to "Happy Timer", happydays_path %></li>
		<li><%= link_to "Дисперсия", capitalcost_path %></li>
		<li><%= link_to "FV", fvcalcs_path %></li>
		<li><%= link_to "Math", math_path %></li>
	</ul>

app/views/simpleapps/capitalcost.html.erb
<div align="center">
<h2>Эксперемент со стоимостью капитала</h2>

<p>Генерируем базовую стоимость активов = <%= @presentprice %> USD, среднюю доходность <%= @averageprof %>.</p>

<p>Получаем дисперсию <%= @dispersia %> из <%=@sravnenie%> сравнений.</p>

<FORM>
<INPUT TYPE="button" onClick="history.go(0)" VALUE="Получить решение!">
</FORM>

<script type="text/javascript">
var chart;
$(document).ready(function() {
   chart = new Highcharts.Chart({
      chart: {
         renderTo: 'container',
         defaultSeriesType: 'column'
      },
      title: {
         text: 'График'
      },
      xAxis: {
         categories: [<%= @sravnenietimes %>]
      },
      yAxis: {
   title: {
            text: 'Стоимость актива, $'
         }
      },
      tooltip: {
         formatter: function() {
            return ''+
                this.series.name +': '+ this.y +'';
         }
      },
      credits: {
         enabled: false
      },
      series: [{
         name: 'Фактическая стоимость актива',
         data: [<%= @newvalues %>]
      }, {
         name: 'Отклонение от ожидаемой стоимости',
         data: [<%= @newvaluesdev %>]
      }, {
           type: 'scatter',
         name: 'Ожидаемая стоимость',
         data: [<%= @fvtimes %>]
      }      ]
   });
   
   
});
   
</script>
<div id="container" style="width: 100%; height: 400px"></div>



</div>
<%= render 'menu' %>

app/views/simpleapps/decision.html.erb
<div align="center">
<h2>Приниматор решений</h2>
<h1><%= @decision %></h1>
<FORM>
<INPUT TYPE="button" onClick="history.go(0)" VALUE="Получить решение!">
</FORM>
</div>
<%= render 'menu' %>

app/views/simpleapps/happydays.html.erb
<div align="center">
<h2>Happy timer</h2>
<script type="text/javascript">
function CountUp(initDate, id){
    this.beginDate = new Date(initDate);
    this.countainer = document.getElementById(id);
    this.numOfDays = [ 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 ];
    this.borrowed = 0, this.years = 0, this.months = 0, this.days = 0;
    this.hours = 0, this.minutes = 0, this.seconds = 0;
    this.updateNumOfDays();
    this.updateCounter();
}
 
CountUp.prototype.updateNumOfDays=function(){
    var dateNow = new Date();
    var currYear = dateNow.getFullYear();
    if ( (currYear % 4 == 0 && currYear % 100 != 0 ) || currYear % 400 == 0 ) {
        this.numOfDays[1] = 29;
    }
    var self = this;
    setTimeout(function(){self.updateNumOfDays();}, (new Date((currYear+1), 1, 2) - dateNow));
}
 
CountUp.prototype.datePartDiff=function(then, now, MAX){
    var diff = now - then - this.borrowed;
    this.borrowed = 0;
    if ( diff > -1 ) return diff;
    this.borrowed = 1;
    return (MAX + diff);
}
 
CountUp.prototype.calculate=function(){
    var currDate = new Date();
    var prevDate = this.beginDate;
    this.seconds = this.datePartDiff(prevDate.getSeconds(), currDate.getSeconds(), 60);
    this.minutes = this.datePartDiff(prevDate.getMinutes(), currDate.getMinutes(), 60);
    this.hours = this.datePartDiff(prevDate.getHours(), currDate.getHours(), 24);
    this.days = this.datePartDiff(prevDate.getDate(), currDate.getDate(), this.numOfDays[currDate.getMonth()]);
    this.months = this.datePartDiff(prevDate.getMonth(), currDate.getMonth(), 12);
    this.years = this.datePartDiff(prevDate.getFullYear(), currDate.getFullYear(),0);
}
 
CountUp.prototype.addLeadingZero=function(value){
    return value < 10 ? ("0" + value) : value;
}
 
CountUp.prototype.formatTime=function(){
    this.seconds = this.addLeadingZero(this.seconds);
    this.minutes = this.addLeadingZero(this.minutes);
    this.hours = this.addLeadingZero(this.hours);
}
 
CountUp.prototype.updateCounter=function(){
    this.calculate();
    this.formatTime();
    this.countainer.innerHTML ="<strong>" + this.years + "</strong> <small>" + (this.years == 1? "year" : "years") + "</small>" +
        " <strong>" + this.months + "</strong> <small>" + (this.months == 1? "month" : "months") + "</small>" +
        " <strong>" + this.days + "</strong> <small>" + (this.days == 1? "day" : "days") + "</small>" +
        " <strong>" + this.hours + "</strong> <small>" + (this.hours == 1? "hour" : "hours") + "</small>" +
        " <strong>" + this.minutes + "</strong> <small>" + (this.minutes == 1? "minute" : "minutes") + "</small>" +
        " <strong>" + this.seconds + "</strong> <small>" + (this.seconds == 1? "second" : "seconds") + "</small>";
    var self = this;
    setTimeout(function(){self.updateCounter();}, 1000);
}
 
window.onload=function(){ new CountUp('November 28, 2009 15:20:00', 'counter'); }
 
</script>
<div id="counter"></div>
	
</div>
<%= render 'menu' %>

app/views/simpleapps/index.html.erb
<%= render 'menu' %>

app/views/simpleapps/kubik.html.erb
<div align="center">
<h2>Просто кубик</h2>
<h1><%= rand(6)+1 %></h1>
<FORM>
<INPUT TYPE="button" onClick="history.go(0)" VALUE="Бросить!">
</FORM>
</div>

<%= render 'menu' %>

app/views/simpleapps/math.html.erb
<script type="text/javascript">
var chart;
$(document).ready(function() {
   chart = new Highcharts.Chart({
      chart: {
         renderTo: 'container',
         defaultSeriesType: 'spline'
      },
         title: {
            text: ''
         },
      xAxis: {
         categories: [<%=@xmass%>]
      },
      yAxis: {

      },
     tooltip: {
         formatter: function() {
                   return '<b>'+ this.series.name +'</b><br/>'+
               this.x +': '+ this.y;
         }
      },
      plotOptions: {
         spline: {
            marker: {
               radius: 4,
               lineColor: '#666666',
               lineWidth: 1
            }
         }
      },
      series: [{
         name: 'x^2',
         marker: {
           enabled: false,
         },
         data: [<%=@ysqrt%>]
   
      }, {
         name: 'six(x)*200+200',
         marker: {
           enabled: false,
         },
         data: [<%=@ysin%>]
      }]
   });
   
   
});
</script>
<div align="center">
<h2>Math examples</h2>


<div id="container" style="width: 100%; height: 400px"></div>

</div>
<%= render 'menu' %>